# Generated by Django 5.1.2 on 2024-11-01 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_category_options_alter_finalexam_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalexam',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.category'),
        ),
    ]
